### ISSUE TITLE
Failed assertion: line 155 pos 12: 'a != 0': is not true.

### ISSUE THREAD

**Issue by zegkljan** [greensopinion/dart-vector-tile-renderer#15]
Rendering of one specific tile failed:

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'package:vector_tile_renderer/src/model/geometry_decoding.dart': Failed assertion: line 155 pos 12: 'a != 0': is not true.

The relevant error-causing widget was: 
  VectorTileLayerWidget VectorTileLayerWidget:file:///home/zegkljan/git/oko-app/lib/main_widget.dart:506:12
When the exception was thrown, this was the stack: 
#2      decodePolygons (package:vector_tile_renderer/src/model/geometry_decoding.dart:155:12)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:180:26)
#4      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:219:26)
#5      new _List._ofOther (dart:core-patch/array.dart:116:43)
#6      new _List.of (dart:core-patch/array.dart:58:18)
#7      new List.of (dart:core-patch/array_patch.dart:53:20)
#8      Iterable.toList (dart:core/iterable.dart:470:12)
#9      TileFeature.paths (package:vector_tile_renderer/src/model/tile_model.dart:59:45)
#10     PolygonRenderer.render (package:vector_tile_renderer/src/features/polygon_renderer.dart:34:30)
#11     FeatureDispatcher.render (package:vector_tile_renderer/src/features/feature_renderer.dart:45:16)
#12     DefaultLayer.render.<anonymous closure> (package:vector_tile_renderer/src/themes/theme_layers.dart:53:33)
#13     TileSpaceMapper.drawInTileSpace (package:vector_tile_renderer/src/features/tile_space_mapper.dart:37:7)
#14     DefaultLayer.render (package:vector_tile_renderer/src/themes/theme_layers.dart:51:29)
#15     Renderer.render.<anonymous closure>.<anonymous closure> (package:vector_tile_renderer/src/renderer.dart:47:20)
#16     List.forEach (dart:core-patch/array.dart:224:8)
#17     Renderer.render.<anonymous closure> (package:vector_tile_renderer/src/renderer.dart:45:29)
#18     Timeline.timeSync (dart:developer/timeline.dart:163:22)
#19     profileSync (package:vector_tile_renderer/src/profiling.dart:16:19)
#20     Renderer.render (package:vector_tile_renderer/src/renderer.dart:34:5)
#21     _VectorTilePainter.paint (package:vector_map_tiles/src/grid/grid_vector_tile.dart:232:38)
#22     RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:13)
#23     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#28     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#29     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#30     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198:7)
#31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
#32     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#33     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#34     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#35     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:443:7)
#36     RenderStack.paint (package:flutter/src/rendering/stack.dart:635:38)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#39     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#40     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#41     RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#44     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#45     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#46     RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#49     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#50     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2397:17)
#51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#53     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79:15)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#56     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#57     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#58     RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#60     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#61     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#62     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#63     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:443:7)
#64     RenderClipRect.paint (package:flutter/src/rendering/proxy_box.dart:1459:23)
#65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#67     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#70     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#72     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#73     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#74     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#75     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#76     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#77     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#78     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#79     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#82     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343:15)
#83     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#84     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#85     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#86     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#87     RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#88     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#90     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847:15)
#91     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#92     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#93     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#94     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#95     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:555:11)
#96     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#97     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#98     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#99     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387:12)
#100    RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1929:15)
#101    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#102    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#103    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#104    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#105    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
#106    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#107    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#108    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#109    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#110    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#111    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:19)
#112    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#113    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#114    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#115    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#116    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#120    _invoke (dart:ui/hooks.dart:151:10)
#121    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#122    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#f6b89
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=1024.5, h=1024.5)
...  size: Size(1024.5, 1024.5)
...  painter: _VectorTilePainter#7aff8(Instance of 'VectorTileModel')
RenderObject: RenderCustomPaint#f6b89
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1024.5, h=1024.5)
  size: Size(1024.5, 1024.5)
  painter: _VectorTilePainter#7aff8(Instance of 'VectorTileModel')
====================================================================================================
```

The `pbf` tile in question is (zipped in `z/x/y.pbf` directory structure) [tile.zip](https://github.com/greensopinion/dart-vector-tile-renderer/files/8428386/tile.zip). The Z/X/Y coords are 14/8847/5549 (GPS 50.099914 N, 14.403638 E), comes from openmaptiles.

**Comment by greensopinion** [comment]
Thanks for the issue. @blaugold this might be of interest to you.

**Comment by blaugold** [comment]
This assertion is triggered when the area of a polygon is 0, and such a polygon should not exist in a tile. We are using the [Shoelace formular](https://en.wikipedia.org/wiki/Shoelace_formula#:~:text=Big%20)%7D%5Cend%7Baligned%7D%7D%7D-,Triangle%20formula,-%5Bedit%5D) here, which is pretty straightforward, so I don't think this is a bug in the geometry decoding code.

Generating vector tiles at different zoom levels involves computing geometry with reduced details, and I suspect that this is an edge case in that process. 

I think a reasonable approach would be to ignore those types of polygons and log a warning.
WDYT? @greensopinion

**Comment by greensopinion** [comment]
Sounds good to me! Ignoring them would make it possible to render tiles despite having artifacts.
